###################  system-web项目配置  ###################
sw:
  multi-datasource-switch: false          # 多数据源是否开启开关
  cache-type: ehcache   # 默认缓存类型
#################### https配置  ###################
server:
  port: 8080
  #ssl:
    #key-store: classpath:www.allenyll.com.jks
    #key-store-password: 58024myself
    #keyStoreType: JKS
###################  数据源配置  ###################
db:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/system_web?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 58024myself
    filters: log4j,wall,mergeStat
  ds2:
    url: jdbc:mysql://132.232.216.185:3306/boot_web?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 58024myself
    filters: log4j,wall,mergeStat

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.sw.common.entity
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false  #驼峰下划线转换
    refresh-mapper: true #刷新mapper 调试神器
  configuration:
    map-underscore-to-camel-case: true #驼峰转下划线
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

###################  spring 配置  ###################
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
  #redis
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    cacheType: redis
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  #fdfs配置 spring boot 1.4使用http/ spring boot 2.0使用servlet
  http:
    multipart:
      #单个文件最大尺寸
      max-file-size: 10mb
      #一个请求文件的最大尺寸
      max-request-size: 50mb
      #设置一个文件上传的临时文件目录
      location: /Users/yuleilei/allenyll/my_prj/tempPhoto

#################### fdfs配置 ###################
fdfs:
  #读取inputsream阻塞时间
  connect-timeout: 600
  so-timeout: 1500
  #tracker地址
  trackerList: 132.232.216.185:22122
  #通过nginx 访问地址
  #fdfs.webServerUrl=http://132.232.216.185:9999/
  #缩略图配置
  thumb-image:
    height: 150
    width: 150
  #spring.jmx.enabled=false
  #通过nginx 访问地址
  resHost: 132.232.216.185
  storagePort: 443
  #获取连接池最大数量
  pool:
    max-total: 200



#################### JWT配置  ###################
jwt:
  header: authorization
  secret: mySecret
  exp: 64800 #token七天不过期
  tokenHead: "Bearer "
  platForm: "JWT_PLATFORM"
  weChat: "JWT_WX"
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
  ignored:
    urls:
        - /test/**
        - /cache/**
        - /wx/**
        - /system-web/**

#################### 微信配置  ###################
auth:
  wechat:
    sessionHost: https://api.weixin.qq.com/sns/jscode2session
    appId: wx95a6a02397595ace
    appSecret: 52c970fbbf76dd8a5ea4b942fca5f6b3
    grantType: authorization_code
    systemWebUrl: http://localhost:8080/system-web/
    username: yll
    password: 123
    mchId:  1529366201
    key: e970d69349bd4b50a033386534860eb3
    orderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
    signType: MD5
    tradeType: JSAPI
